GET http://localhost:3037/users

####

POST http://localhost:3037/users/
Content-Type: application/json

  {
    "fName": "Luna",
    "lastName": "Pettersson",
    "userName": "LuPe",
    "email": "Luuna@gmail.com",
    "password": "123"
  }


####
GET http://localhost:3037/users/607c66d830d6821bbc08578c