GET http://localhost:3037/users

####

POST http://localhost:3037/users/
Content-Type: application/json

  {
    "fName": "Leafar",
    "lastName": "Johnsson",
    "userName": "user2",
    "email": "leafar@gmail.com",
    "password": "pass"
  }
